apiVersion: batch/v1
kind: Job
metadata:
  name: pi-job
spec:
  template:
    spec:
      containers:
        - name: pi-container
          image: perl
          command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
      restartPolicy: Never #não reinicie o pod em nenhum momento
  backeoffLimit: 3 #numero de tentativasantes de ter um status de falha
