apiVersion: v1
kind: Pod
metadata:
  name: pi-pod
spec:
  containers:
    - name: pi-container
      image: perl
      command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
