apiVersion: apps/v1 #Grupo da api
kind: ReplicaSet
metadata: #metadata do replicaset
  name: portal-noticias-replicaset
spec:
  replicas: 3 #numero de replicas do replicaset
  selector: #quais recursos ele deve gerir
    matchLabels:
      app: portal-noticias

  template: #qual o modelo/padrão do replica set
    metadata: #dados do pod
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-configmap
