apiVersion: v1
kind: Service
metadata:
  name: svc-pod-2
spec:
  type: ClusterIP #tipo do service
  selector: #seleciona as labels para o serviço se conectar
    app: segundo-pod
  ports: #portas para entrada e saida
    #todas as informações que entram pela 80 são redirecionadas para a porta 80 que possuem as labels
    - port: 8080 #porta que queremos ouvir
      targetPort: 80 #porta que enviaremos
