apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  clusterIP: None
  selector:
    app: mysql

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10 #tempo de espera após mandar o pod finalizar para ele salvar as informações antes de fechar
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
              name: mysql # nome da porta
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: senhas

            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DB_DATABASE
                  name: dados
          volumeMounts:
            - name: mysql-ps
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-ps
          persistentVolumeClaim:
            claimName: volume-mysql
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-mysql
spec:
  schedule: "0 3 * * *"
  jobTemplate: # o que será executado
    spec:
      template:
        spec:
          containers:
            - name: mysqldump
              image: leonardosartorello/mysqldump:v4
              env:
                - name: MYSQL_ENV_DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: dados
                      key: DB_HOST

                - name: MYSQL_ENV_DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: senhas
                      key: DB_PASSWORD

                - name: MYSQL_ENV_DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: senhas
                      key: MYSQL_ENV_DB_USER
          restartPolicy: OnFailure
